# Generated by Django 5.1.4 on 2025-06-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=32, unique=True)),
                ('account_type', models.CharField(choices=[('MAIN', 'Main'), ('SAVINGS', 'Savings'), ('SUPPORT', 'Support'), ('INVESTMENT', 'Investment'), ('CREDIT', 'Credit'), ('BUSINESS', 'Business')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('PLN', 'Pln'), ('USD', 'Usd'), ('EUR', 'Eur'), ('GBP', 'Gbp')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
