# Generated by Django 5.1.4 on 2025-09-22 20:40

import apps.core.utils.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=apps.core.utils.identifiers.str_uuid, max_length=36, unique=True),
        ),
    ]
