# Generated by Django 5.1.4 on 2024-12-10 09:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 10)),
        ),
    ]
