# Generated by Django 5.1.4 on 2024-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0004_category_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_constant',
            field=models.BooleanField(default=False),
        ),
    ]
