# Generated by Django 5.1.4 on 2025-10-03 08:03

from django.db import migrations, models
from datetime import datetime

def generate_slug(apps, schema):
    transaction_model = apps.get_model('transactions', 'Transaction')
    for transaction in transaction_model.objects.all():
        transaction.created_at = datetime.combine(transaction.date, datetime.min.time())
        transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_account_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(generate_slug),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
