# Generated by Django 5.1.4 on 2025-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_plannedtransaction_created_at_transaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedtransaction',
            old_name='is_constant',
            new_name='is_monthly_payment',
        ),
        migrations.RemoveField(
            model_name='plannedtransaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_constant',
        ),
        migrations.AddField(
            model_name='plannedtransaction',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plannedtransaction',
            name='scheduled_at',
            field=models.DateField(db_index=True),
        ),
    ]
