# Generated by Django 5.1.4 on 2025-01-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_inactivity_notification',
            field=models.BooleanField(default=False),
        ),
    ]
