# Generated by Django 5.1.4 on 2025-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sent_inactivity_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sent_inactivity_notification',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
