# Generated by Django 5.1.4 on 2025-01-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_sent_inactivity_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sent_inactivity_notification',
        ),
    ]
