# Generated by Django 5.1.4 on 2025-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_sent_inactivity_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_inactivity_notification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
