# Generated by Django 5.1.4 on 2025-01-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_sent_inactivity_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sent_inactivity_notification',
            new_name='inactivity_notification_sent_at',
        ),
    ]
