# Generated by Django 5.1.4 on 2024-12-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='operation_type',
        ),
    ]
