# Generated by Django 5.1.4 on 2024-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_purpose_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
