# Generated by Django 5.1.4 on 2024-12-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='purpose',
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='goal',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='savings',
                to='savings.goal',
            ),
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
