# Generated by Django 5.1.4 on 2025-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'savings',
            '0001_squashed_0005_remove_goal_purpose_remove_saving_purpose_goal_title_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
