# Generated by Django 5.1.4 on 2025-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_goal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
